vtex-apps/return-app

CHANGELOG.MD
node/package.json
node/yarn.lock
react/store/MyReturnsPageAdd.tsx

- Currently when an order is being returned through the OMS it can also be returned through the RMA
- Only show show orders that have not been returned through the OMS and also orders that haven't been requested for return
- `order.invoiceInput`, is available only if the order has already been returned.

[USAAPPTEAM-32] Show orders only if they haven't been returned

---

CHANGELOG.MD
graphql/types/ProductReturned.graphql
node/clients/mdFactory.ts
node/resolvers/createReturnRequest.ts
node/resolvers/deleteReturnRequest.ts
react/StoreMyReturnsPageAdd.tsx
react/admin/ReturnSettingsWrapper.tsx
react/store/MyReturnsPageAdd.tsx
react/store/graphql/createReturnRequest.gql
react/store/graphql/deleteReturnRequest.gql
react/typings/vtex.return-app.d.ts

This PR connects the front end module to create an new RMA to the Graphql handling the process. It allows us to replace the several calls coming back and froth from the browser to the server the app was using before, making it prone to error.
The logic was placed in a functional wrapper component, which we can use to slowly replace the class one.
The component that needs more details in the review is: `react/store/MyReturnsPageAdd.tsx`.
The previous methods making the requests to create 1. the return request; 2. the history message; 3 the products requests; and 4. send email, were replaced by the single to to the back end using Graphql.
Login in the store. Create a new request. All should work fine and the request will be available when you return to the main page.
The branch is linked in …

Create rma graphql frontend

---

CHANGELOG.md
graphql/schema.graphql
manifest.json
react/store/graphql/createReturnRequest.gql

This PR fixes the error preventing users using a non-VTEX email to create a return request. The error was due to a request to get the order information. The app was passing `STORE_TOKEN` to the request. Changing to `AUTH_TOKEN` fixed the problem.
A new version was already released `v2.18.2` and it's install on powerplanet. It can be tested here: https://www.we-demostore.com/es

Fix error 403 when creating a new request

---

CHANGELOG.md
common/constants.ts

In admin section where users can view and set the "Returns List" table
Returns page has list of items that the customers want to return, when click on the square icon beside each item to view its history it was not working as expected, so this fix is to indexation `refundId` in `returnRequests` schema.
**Admin**
Go to Applications, from `Returns` section select `Request` there you will find a list of all items that all the client users wanted to return so you can use this [link](https://returnhistory--yamamayqa.myvtex.com/admin/returns/requests/) to test click on any one of the item either on square or the eye icon to view the history of each item
[Workspace](https://returnhistory--yamamayqa.myvtex.com)
**Admin:**

Fix: Add refundId to returnRequests

---

CHANGELOG.md
react/components/RequestInfo.tsx
react/store/MyReturnsPageAdd.tsx

Hot fix to change the value passed to `paymentMethod` when creating RMA. The value was bigger than the limit defined by the schema. Now, we pass a string `sameAsOrder`. When the value matches, we show a translatable message for the store and admin users.

Hot fix/same as order payment method

---

node/clients/masterdata.ts
node/index.ts
node/middlewares/api/addComment.ts
node/middlewares/api/changeProductStatus.ts
node/middlewares/api/checkStatus.ts
node/middlewares/api/getList.ts
node/middlewares/api/getRequest.ts
node/middlewares/api/updateStatus.ts
node/middlewares/api/verifyPackage.ts
node/middlewares/createGiftCard.ts
node/middlewares/createRefund.ts
node/middlewares/errorHandler.ts
node/middlewares/generateReturnsSchema.ts
node/middlewares/getGiftCard.ts
node/middlewares/getOrder.ts
node/middlewares/getOrders.ts
node/middlewares/getRequests.ts
node/middlewares/getSkuById.ts
node/middlewares/receiveCategories.ts
node/middlewares/receiveDocuments.ts
node/middlewares/returnAppGetSchemas.ts
node/middlewares/saveMasterdataDocuments.ts
node/middlewares/saveMasterdataPartialDocuments.ts
node/middlewares/sendMail.ts
node/middlewares/updateGiftCard.ts
node/resolvers/deleteReturnRequest.ts

What this PR changes:
Improve error handling and use splunk logger method in order to see on the platform.
How to test it:
[this workspace](https://zekiqa--vtexspain.myvtex.com/account#/my-returns).
Add a `throw new Error('any message')` on any defined route go to to the given workspace reload the page and then you can see the error on splunk.
`receiveDocuments.ts` is a good file to test because it loads on the root of the app.

Handle errors

---

CHANGELOG.md
react/store/MyReturnsPageAdd.tsx

This is a hot fix trying to avoid the mismatch between products returned and the order id associated to them. In the investigation, I noticed that if an order takes too long to resolve when the app is listing all orders available to be returned, when it's done, it will overwrite the products been seeing by the user if they have already selected an order. It can be seen in the video below. The order [1216000039663-01](https://vtexspain.myvtex.com/admin/checkout/#/orders/1216000039663-01?orderBy=creationDate,desc&page=1&q=1216000039663-01&f_creationDate=creationDate:%5B2021-09-08T22:00:00.000Z%20TO%202022-03-09T22:59:59.999Z%5D) has a Star War figure as product, but it show a sun glasses as the product to be returned.
https://user-images.githubusercontent.com/38737958/157684712-8a4a700d-a0e4 …

Hot fix/order rma mismatch

---

messages/context.json
messages/en.json
node/package.json
node/yarn.lock
react/StoreReturnApp.ts
react/package.json
react/store/StoreMyReturnsAdd.ts
react/store/StoreReturnAppRouter.tsx
react/store/createNewRMA/OrderToRMADetails.tsx
react/store/createNewRMA/components/RenderReasonDropdown.tsx
react/store/graphql/getStoreSettings.gql
react/store/hooks/useStoreSettings.ts
react/store/provider/StoreSettingsProvider.tsx
react/yarn.lock
store/interfaces.json

This PR adds a custom hook `useStoreSettings` that allows any child component of `OrderToRMADetails` to read the app settings. It will  be useful to avoid prop drilling or fetching it in every single component that will use settings to create the UI.

V3 store settings provider

---

graphql/types/OrderToReturn.graphql
node/package.json
node/utils/createOrdersToReturnSummary.ts
node/yarn.lock
react/package.json
react/store/createReturnRequest/ReturnDetailsContainer.tsx
react/store/createReturnRequest/components/PaymentMethods.tsx
react/store/createReturnRequest/components/ReturnDetails.tsx
react/store/createReturnRequest/graphql/getOrderToReturnSummary.gql
react/yarn.lock

This code brings a new flag on the `OrderToReturnSummary` resolver to show if the order can be refunded using card or not - it should be only possible to refund card if the payment was made using a card.
In this [workspace](https://v3rmacardflag--powerplanet.myvtex.com/admin/graphql-ide) select the return app in the GraphQL ide.
The query below will bring the result for the new flag. The first order, placed using credit card, should return `true`.  The second one, placed with promissory, should return false.
```
query orderOne {
orderToReturnSummary(orderId: "1229173257363-01") {
paymentData {
canRefundCard
}
}
}
query orderTwo {
orderToReturnSummary(orderId: "1224161013423-01") {
paymentData {
canRefundCard
}
}
}
```

Feat: Add property to know if the refund can be done usning credit card

---

CHANGELOG.md
messages/context.json
messages/en.json
node/yarn.lock
react/components/RequestForm.tsx
react/components/RequestInformation.tsx

What this PR changes:
Internationalize the payment method message on `RequestInformation` and add linebreak variable to FormattedMessage on `RequestForm`.
How to test it:
[this workspace](https://fix--vtexspain.myvtex.com/account#/my-returns/add)
Linebreak example:
Internationalized message:
If you want to test the linebreak this is the mutation:
```
mutation Save($saveArgs: SaveArgsV2!) {
saveV2(args: $saveArgs)
}
```
```
{
"saveArgs": {
"to": "it-IT",
"messages": [
{
"srcLang": "en-DV",
"srcMessage": "returns.defaultPaymentMethod",
"context": "vtex.return-app@2.x",
"targetMessage": "Il rimborso verrà emesso sul metodo di pagamento utilizzato per questo ordine.{linebreak}Nel caso tu abbia pagato con contrassegno inserisci il tuo codice IBAN e i dati dell'intestatario del conto nel campo …
```

feat: add messages internationalization and linebreak

---

graphql/types/ReturnRequest.graphql
masterdata/returnRequest/schema.json
node/package.json
node/resolvers/createReturnRequest.ts
node/yarn.lock
react/graphql/getReturnRequestDetails.gql
react/package.json
react/yarn.lock

Changes in the schema:
1. Removed `verifiedItems` from `items`.
Previously, the key would be used to control if an item had been already verified (different than `null`) and how many items had been verified for that item. However, the field being `null` or `0` could lead to bugs when checking falsy values and make it difficult to understand the real meaning of the field.
Alternatively, the app can use the `RefundData` to calculate the items that have been verified. The `RefundData` object will be created when the status `packageVerified` is submitted. This way, we can calculate the items verified in the browser using the object. Also, a request with status `denied` means that all items were denied.
2. Change the way to save comments.
Previously, the request could have several objects with …

Refactor: Update RMA schema

---

graphql/types/ReturnRequest.graphql
masterdata/returnRequest/schema.json
node/package.json
node/resolvers/ReturnRequestResponse.ts
node/resolvers/createReturnRequest.ts
node/utils/createItemsToReturn.ts
node/utils/createRefundableTotals.ts
node/yarn.lock
react/graphql/getReturnRequestDetails.gql
react/package.json
react/yarn.lock

This code changes the resolver to create a new request, and calculates and brings the refundable values for it. The values are broken as `items`, `shipping`, and `tax` and every item in the request now has the `sellingPrice` and `tax`. The taxes are either from `item.tax` (from order) or calculated from the TAXHUB value (non-native tax engines). In some cases I found (unileverb2b), the value coming from the TAXHUB for every item is the total for that item (not per unit). The current implementation also follows this logic, so I handled it like that. The `item.tax` is a unit tax.
This [workspace](https://v3rmavalues--powerplanet.myvtex.com/) has the branch linked. One can create a new request. When checking it's object, the amounts should be present.

V3rmavalues

---

node/package.json
node/resolvers/createReturnRequest.ts
node/utils/createRefundableTotals.ts
node/yarn.lock
react/package.json
react/yarn.lock

What this PR changes:
Add the functionality to calculate a proportional shipping according to the returned items. This is done by multiplying the returned items amount with the total shipping amount, divided the total value of the order minus discounts.
How to test it:
[workspace](https://pickup--powerplanet.myvtex.com/account?__bindingAddress=www.we-demostore.com/es#/my-returns)
Example 1: 
`OrderId = 1234661288883-01`
`requestId = 43fbd375-dc18-11ec-835d-12de88b0135b`
Here we can see that the proportional shipping is calculate it correctly because we returned two items on an order of 5 same items. The result is 2/5, on this case 200 cents is the proportional shipping value for those items.
Example 2:
`OrderId = 1234651703184-01`
1. `requestId =  b90f62a6-dc10-11ec-835d-02e6b01173ed`
2. …

feat: add proportional shipping value functionality

---

CHANGELOG.md
manifest.json
node/index.ts
node/middlewares/getExtraSettings.ts
node/package.json
node/service.json
node/typings/vtex.return-app.d.ts
node/yarn.lock
react/common/fetch.tsx
react/components/ProductsTable.tsx
react/components/RequestForm.tsx
react/components/RequestInformation.tsx
react/package.json
react/store/MyReturnsPageAdd.tsx
react/yarn.lock

[WORKSPACE](https://sanz--vtexspain.myvtex.com/)
Leveraging the APPS client, a new settings schema was added to the manifest. Allowing customisation of the app without the need of modifying the current masterdata settings schema.
This was included to accomodate a new setting called `displayConditionSelector`, which hides the product condition select from the return request page; by default, this setting is considered `true`, making this change transparent and a minor change.
For minimum impact, I decided to add an extra fetch that resolves the settings and adds them to the original ones, allowing to add more in the future without breaking current implementations.
**A new endpoint and middleware was created for this.**
```js
Promise.all([this.getSettings(), …
```

Extra settings apart from settings MD document

---

CHANGELOG.md
react/admin/ReturnForm.tsx
react/components/ProductsTable.tsx
react/store/ReturnsDetails.tsx

What is the purpose of this PR?
Fix total amount of products price by calculating directly the sum of each product value instead of relying on the totalPrice from the return request.
How to test it?
Admin
[workspace](https://total--vtexspain.myvtex.com/admin/returns/2a7d42e5-dfe8-11ec-835d-120db15413bb/details/)
Store
[workspace](https://total--vtexspain.myvtex.com/account#/my-returns/details/c7fe72a1-af9b-11ec-835d-123072a6b6a3)

fix: display total products value directly

---

react/common/constants/returnsRequest.ts
react/store/createReturnRequest/components/ItemsDetails.tsx
react/store/createReturnRequest/components/ItemsList.tsx
react/store/createReturnRequest/components/RenderReasonDropdown.tsx
react/store/createReturnRequest/components/ReturnDetails.tsx
react/store/utils/generateCustomReasonOptions.ts

If the account holder wants to have custom reasons, we will replace the default ones with those.
These custom entries can be translated, so the value/label of the selector will take the user's locale and find if the translation exists, or set the default one as it.
The following WS has 2 custom reasons, one without translation and one with a translation for each available locale.
Create a return request and see how one is always the same and the other one reacts to the user's locale.
[Workspace](http://sanz--elefantqa.myvtex.com/)

[Frontend] Replace reasons with custom reasons, when available

---

messages/context.json
messages/en.json
react/admin/ReturnDetails/ReturnDetailsContainer.tsx
react/admin/ReturnDetails/components/ItemDetails/itemDetailsSchema.tsx
react/admin/ReturnDetails/components/ReturnValues/ApprovedValues.tsx
react/admin/ReturnDetails/components/ReturnValues/RequestedValues.tsx
react/admin/ReturnDetails/components/ReturnValues/ReturnValues.tsx
react/admin/ReturnDetails/components/ReturnValues/TotalContainer.tsx
react/admin/ReturnDetails/components/ReturnValues/TotalWrapper.tsx
react/admin/graphql/returnDetailsAdminFragment.gql

This PR adds a component to show the requested and refunded amount for a return request.
The branch is linked in this [workspace](https://rmav3returnvalues--powerplanet.myvtex.com/). When seeing a return request details page, there will be a new component showing the totals that were requested. If the order is on status `amountRefunded` or `packageVerified`, there will another box with the totals there were approved or refunded. To test that scenario, one just needs to update the order status.

V3 return values

---

CHANGELOG.md
node/middlewares/getOrders.ts

What this PR changes:
This PR is encoding the email value of the URI to avoid breaking the URL. The issue is mentioned here => https://github.com/vtex-apps/return-app/issues/121
How to test it:
[this workspace](https://v2validation--vtexspain.myvtex.com/account#/my-returns/add).

fix: encodeURI email value

---

graphql/types/ReturnRequest.graphql
masterdata/returnRequest/schema.json
node/package.json
node/resolvers/createReturnRequest.ts
node/utils/createOrUpdateStatusPayload.ts
node/yarn.lock
react/admin/ReturnDetails/components/StatusTimeline/CommentList.tsx
react/admin/graphql/returnDetailsAdminFragment.gql
react/package.json
react/yarn.lock

Add the user comments to the return request timeline when the request is created
[Workspace](https://returnappusercomments--powerplanet.myvtex.com/admin)

V3 add user comments to timeline

---

messages/context.json
messages/en.json
react/common/components/returnList/ListTable.tsx
react/common/components/returnList/ListTableFilter.tsx
react/common/components/returnList/ListTableSchema.tsx
react/common/components/returnList/StatusActionMenu.tsx
react/hooks/useReturnRequestList.ts
react/store/ReturnRequest/StoreReturnList.tsx
react/store/createReturnRequest/components/ConfirmAndSubmit.tsx

[WORKSPACE](https://sanzstore--powerplanet.myvtex.com)
---
Fixed: When successfully creating a return request, in My account, the alert CTA to navigate back to the request return list won't trigger a re-render, and the new request will be missing until refreshing the page.
---
Added: The return list in my account is now more readable, the Request ID field and filter were removed.
---
Added: The admin return list now displays a tooltip that states that the customer now needs to access the detail to retrieve the request ID.
---
Fixed: navigation links for both domains (admin/store) now redirect accordingly
---
Fixed: buttons now are displayed as disabled instead of spinning when the request list data is loading

Request list visibility changes

---

react/common/components/returnList/ListTableSchema.tsx
react/store/createReturnRequest/components/ReturnDetails.tsx

Change format date  to numeric on `My returns` and `Return Details` components to avoid differences with different countries.
[Workspace](https://date--powerplanet.myvtex.com/account?__bindingAddress=www.we-demostore.com/es#/my-returns)
Before:
After:

refactor: format date numeric

---

CHANGELOG.md
react/admin/ReturnDetails/components/VerifyItems/verifyItemsTableSchema.tsx
react/common/components/ReturnDetails/ItemDetails/ItemDetailsList.tsx
react/common/components/ReturnDetails/ItemDetails/itemDetailsSchema.tsx
react/common/components/ReturnDetails/RequestCancellation.tsx
react/common/components/ReturnDetails/StatusHistory.tsx
react/common/components/returnList/ListTable.tsx
react/common/components/returnList/ListTableFilter.tsx
react/common/components/returnList/ListTableSchema.tsx
react/store/ReturnRequest/StoreReturnDetails.tsx
react/store/ReturnRequest/StoreReturnList.tsx
react/store/createReturnRequest/CreateReturnRequest.tsx
react/store/createReturnRequest/components/AddressDetails.tsx
react/store/createReturnRequest/components/ConfirmAndSubmit.tsx
react/store/createReturnRequest/components/ConfirmComment.tsx
react/store/createReturnRequest/components/ConfirmContactDetails.tsx
react/store/createReturnRequest/components/ConfirmPaymentMethods.tsx
react/store/createReturnRequest/components/ConfirmPickupAddressDetails.tsx
react/store/createReturnRequest/components/ContactDetails.tsx
react/store/createReturnRequest/components/ItemsDetails.tsx
react/store/createReturnRequest/components/ItemsList.tsx
react/store/createReturnRequest/components/PickupPointSelector.tsx
react/store/createReturnRequest/components/ReturnDetails.tsx
react/store/createReturnRequest/components/ReturnInformationTable.tsx
react/styles.global.css

Adjusted all pages for better UI/UX under 639px (phone)
[Workspace](https://sanzmobile--powerplanet.myvtex.com/)
- Removed both filters and jump to page
- Page header now has a consistent padding
- Page header now has a consistent padding
- Table rows now have consistent widths
- CTAs are now more accesible to the user
- Table doesn't overflow anymore
- Table actions are now more accesible to the user
- Card containing summary now has consistent widths
- CTAs are now more accesible to the user

Responsive store returns

---

CHANGELOG.md
node/package.json
node/services/createReturnRequestService.ts
node/yarn.lock
react/package.json
react/yarn.lock

Remove IBAN and accountHolderNumber if refund method different than bank [Back end]
[Workspace](https://bankrefundmethod--vtexspain.myvtex.com/admin/graphql-ide)
Create a return via graphQL and then look at the request with the ID. If the payment method is different than bank it shouldn't have the accountHolderName and the iban.
```
mutation createReturnRequest($returnRequest: ReturnRequestInput!) {
createReturnRequest(returnRequest: $returnRequest) {
returnRequestId
}
}
```
```
{
"returnRequest": {"items": [{
"orderItemIndex": 0,
"quantity": 1,
"returnReason": {
"reason": "Wrong type"
},
"condition": "newWithBox"
}],
"orderId": "1250972984721-01",
"refundPaymentData": {
"refundPaymentMethod": "giftCard",
"accountHolderName": "Testing guy",
"iban": "DE3242545"
},
"pickupReturnData": { …
```

feat: remove iban and name when payment method diff bank

---

node/utils/isValidIBANNumber.ts
node/utils/validatePaymentMethod.ts

Add Backend IBAN validation
Place a random IBAN it should trigger the apollo graphql error.
[Workspace](https://backend--vtexspain.myvtex.com/account#/my-returns/add)
Note: I placed a prefer-early-return flag to avoid esLint warning. Do you think there is a better way? 
```
// eslint-disable-next-line vtex/prefer-early-return
if (refundPaymentMethod === 'bank') {
if (!iban) {
throw new ResolverError('IBAN is required', 400)
}
if (!accountHolderName) {
throw new ResolverError('Account holder name is required', 400)
}
if (!isValidIBANNumber(iban)) {
throw new ResolverError('IBAN is not valid', 400)
}
}
```

feat: add IBAN validation to backend

---

CHANGELOG.md
node/utils/createItemsToReturn.ts
react/common/components/ReturnDetails/ItemDetails/itemDetailsSchema.tsx

The `refId` is a non required field in the catalog, but the schema for the return asks for it. Requests for items missing it were failing.
Request created with an item that doesn't have `refId` (Powerplanet, product: 47211):
I considered changing the master data schema and the graphql type for the returned items, making it non required and nullable, respectively. However, changing the graphql type from `String!` to `String` requires a new major. The implementation suggested here avoids that.

[Fix] Allow return request for items with undefined refId's

---

manifest.json
node/clients/returnapp.ts
node/package.json
node/yarn.lock

Recently, the Order Management system for VTEX changed their permissions system. Before it was possible to use the `OMSViewer` policy in the `manifest.json` file to list orders, now you need the `ListOrders` policy for that.
This caused some services in the Returns App to fail with a "Not found message"
Open the workspace and see data returned as expected
[Workspace](https://fixlistorders--yamamay.myvtex.com/returns/getOrders/clientEmail=francisco.benitez@vtex.com.br)

Fix List Orders permission error
